### ISSUE TITLE
add video?

### ISSUE THREAD

**Issue by BluePrintRandom** [underpig1/neuro-bge#1]
could you add a usage video ?

do you want to talk to the upbge team about maybe teaming up?

**Comment by underpig1** [comment]
@BluePrintRandom,
I added a short tutorial to learn the basics of NeuroBGE with a game:
[Blender 2.8: Creating an FPS Game with NeuroBGE](https://www.youtube.com/watch?v=F63lMZXwCV8)

I would be happy to talk to the UPBGE team about teaming up.
Enjoy!

**Comment by BluePrintRandom** [comment]
Cool - maybe link in readme? then I will close
