### ISSUE TITLE
blender crashes when enabeling addon

### ISSUE THREAD

**Issue by GuyJan** [underpig1/neuro-bge#7]
I installed the zipped add-on under preferences, but as soon as I click on Enable, Blender 2.9 closes (crashes) without any comments. I have Windows 10 64 bit as OS

**Comment by GrahamBablam** [comment]
Having same problem

**Comment by adamalbu** [comment]
Same

**Comment by brunomolteni** [comment]
same over here! running Windows 10

**Comment by underpig1** [comment]
This issue has been resolved in v1.0.0. Feel free to download the new version [here](https://github.com/underpig1/neuro-bge/releases/tag/v1.0.0)!
